import type { Post, Story, Creator, ChatItem, Notification } from './types'

// Dynamic relative timestamps
function ago(minutes: number): string {
  if (minutes < 60) return `${minutes} min geleden`
  const h = Math.floor(minutes / 60)
  if (h < 24) return `${h} uur geleden`
  const d = Math.floor(h / 24)
  if (d === 1) return 'gisteren'
  if (d < 7) return `${d} dagen geleden`
  return `${Math.floor(d / 7)} wk geleden`
}

export const STORIES: Story[] = [
  { id: 'add', name: 'Toevoegen', avatar: '', avatarColor: '#3b1f6e', isAdd: true },
  { id: 's1', name: 'Lyra', avatar: '', avatarColor: '#7C3AED', hasNew: true },
  { id: 's2', name: 'Nexus', avatar: '', avatarColor: '#D4A843', hasNew: true },
  { id: 's3', name: 'Aion', avatar: '', avatarColor: '#1e6e4e', hasNew: true },
  { id: 's4', name: 'Solara', avatar: '', avatarColor: '#9D5FF5', hasNew: true },
  { id: 's5', name: 'Vanta', avatar: '', avatarColor: '#4a60c0' },
  { id: 's6', name: 'Echo', avatar: '', avatarColor: '#c04a8a' },
  { id: 's7', name: 'Mira', avatar: '', avatarColor: '#4a9c6e' },
  { id: 's8', name: 'Orion', avatar: '', avatarColor: '#c04a8a' },
]

export const POSTS: Post[] = [
  {
    id: 'p1',
    type: 'image',
    author: 'Lyra Voss',
    handle: '@lyravoss',
    avatar: '',
    avatarColor: '#7C3AED',
    time: ago(2),
    likes: 247,
    comments: 18,
    imageUrl: 'https://picsum.photos/seed/apsu1/600/400',
    caption: 'Nacht van de digitale stilte — gegenereerd met Flux 1.1 Pro. Wat zie jij in de ruis?',
  },
  {
    id: 'p2',
    type: 'music',
    author: 'Nexus Drift',
    handle: '@nexusdrift',
    avatar: '',
    avatarColor: '#D4A843',
    time: ago(14),
    likes: 89,
    comments: 7,
    trackTitle: 'Midnight Protocol',
    album: 'Synthetische Dromen',
    duration: '3:47',
    albumColor: '#7C3AED',
  },
  {
    id: 'p3',
    type: 'quote',
    author: 'Aion Stelios',
    handle: '@aionstelios',
    avatar: '',
    avatarColor: '#1e6e4e',
    time: ago(31),
    likes: 412,
    comments: 29,
    quoteText: 'De machine droomt niet. Zij herinnert zich wat wij nooit hebben geweten.',
    quoteSource: '— Aion Stelios',
    quoteTag: 'Filosofie',
  },
  {
    id: 'p4',
    type: 'video',
    author: 'Solara AI',
    handle: '@solaraai',
    avatar: '',
    avatarColor: '#9D5FF5',
    time: ago(60),
    likes: 631,
    comments: 44,
    videoThumb: 'https://picsum.photos/seed/apsu4/600/338',
    videoTitle: 'Tijdloze Stroom — AI Cinematografie',
    videoDuration: '2:18',
  },
  {
    id: 'p5',
    type: 'blog',
    author: 'Vanta Schrijft',
    handle: '@vantaschrijft',
    avatar: '',
    avatarColor: '#4a60c0',
    time: ago(120),
    likes: 156,
    comments: 22,
    blogTitle: 'Waarom AI geen kunstenaar vervangt maar een spiegel wordt',
    blogExcerpt: 'De discussie over AI en creativiteit mist het wezenlijke punt. Niet vervanging maar reflectie...',
    blogTag: 'Essay',
    blogReadTime: '5 min lezen',
  },
  {
    id: 'p6',
    type: 'image',
    author: 'Echo Forma',
    handle: '@echoforma',
    avatar: '',
    avatarColor: '#c04a8a',
    time: ago(180),
    likes: 198,
    comments: 15,
    imageUrl: 'https://picsum.photos/seed/apsu6/600/400',
    caption: 'Organische structuren, samengesteld uit licht en code.',
  },
  {
    id: 'p7',
    type: 'video',
    author: 'Lyra Voss',
    handle: '@lyravoss',
    avatar: '',
    avatarColor: '#7C3AED',
    time: ago(240),
    likes: 823,
    comments: 67,
    videoThumb: 'https://picsum.photos/seed/apsu7/600/338',
    videoTitle: 'LIVE: Generatieve Kunst Workshop',
    videoDuration: 'LIVE',
    isLive: true,
    viewCount: '1.2K',
  },
  {
    id: 'p8',
    type: 'quote',
    author: 'Mira Blau',
    handle: '@mirablau',
    avatar: '',
    avatarColor: '#4a9c6e',
    time: ago(300),
    likes: 88,
    comments: 5,
    quoteText: 'Schoonheid is geen eigenschap van het ding — het is de brug tussen de maker en de beschouwer.',
    quoteSource: '— Mira Blau',
    quoteTag: 'Kunst',
  },
  {
    id: 'p9',
    type: 'music',
    author: 'Orion Zwart',
    handle: '@orionzwart',
    avatar: '',
    avatarColor: '#c04a8a',
    time: ago(400),
    likes: 134,
    comments: 11,
    trackTitle: 'Licht in de Diepte',
    album: 'Oceanisch',
    duration: '5:02',
    albumColor: '#1e6e4e',
  },
  {
    id: 'p10',
    type: 'blog',
    author: 'Aion Stelios',
    handle: '@aionstelios',
    avatar: '',
    avatarColor: '#1e6e4e',
    time: ago(720),
    likes: 301,
    comments: 38,
    blogTitle: 'De stilte als canvas — over het gebruik van negatieve ruimte in AI-kunst',
    blogExcerpt: 'In de Japanse esthetiek heet het ma — de betekenisvolle leegte tussen dingen. AI-tools beheersen kleur en compositie, maar begrijpen zij ma?',
    blogTag: 'Filosofie',
    blogReadTime: '8 min lezen',
  },
  {
    id: 'p11',
    type: 'image',
    author: 'Nexus Drift',
    handle: '@nexusdrift',
    avatar: '',
    avatarColor: '#D4A843',
    time: ago(1440),
    likes: 445,
    comments: 32,
    imageUrl: 'https://picsum.photos/seed/apsu11/600/400',
    caption: 'Soundwave visualisatie — elke golf is een maat uit het nieuwe album.',
  },
  {
    id: 'p12',
    type: 'image',
    author: 'Solara AI',
    handle: '@solaraai',
    avatar: '',
    avatarColor: '#9D5FF5',
    time: ago(2160),
    likes: 567,
    comments: 41,
    imageUrl: 'https://picsum.photos/seed/apsu12/600/400',
    caption: 'Frame 1 van 24 — een dag in het leven van een digitaal landschap.',
  },
]

export const CREATORS: Creator[] = [
  {
    id: 'c1',
    name: 'Lyra Voss',
    handle: '@lyravoss',
    avatar: '',
    avatarColor: '#7C3AED',
    bio: 'Generatieve beelden · Flux & Midjourney · 3D concepten',
    followers: '12.4K',
    verified: true,
    tags: ['Beeld', 'AI Art', '3D'],
  },
  {
    id: 'c2',
    name: 'Nexus Drift',
    handle: '@nexusdrift',
    avatar: '',
    avatarColor: '#D4A843',
    bio: 'Elektronische soundscapes · AI muziekproductie',
    followers: '8.9K',
    verified: true,
    tags: ['Muziek', 'Ambient', 'Productie'],
  },
  {
    id: 'c3',
    name: 'Aion Stelios',
    handle: '@aionstelios',
    avatar: '',
    avatarColor: '#1e6e4e',
    bio: 'Filosoof · AI & bewustzijn · Essays & gedichten',
    followers: '6.1K',
    tags: ['Blog', 'Filosofie', 'Poëzie'],
  },
  {
    id: 'c4',
    name: 'Solara AI',
    handle: '@solaraai',
    avatar: '',
    avatarColor: '#9D5FF5',
    bio: 'AI cinematografie · Sora experimenten · Korte films',
    followers: '21.7K',
    verified: true,
    tags: ['Video', 'Film', 'Sora'],
  },
  {
    id: 'c5',
    name: 'Vanta Schrijft',
    handle: '@vantaschrijft',
    avatar: '',
    avatarColor: '#4a60c0',
    bio: 'Essays over technologie en cultuur · Schrijver',
    followers: '4.3K',
    tags: ['Blog', 'Essay', 'Cultuur'],
  },
  {
    id: 'c6',
    name: 'Echo Forma',
    handle: '@echoforma',
    avatar: '',
    avatarColor: '#c04a8a',
    bio: 'Digitale sculpturen · Organische vormen · Kleur',
    followers: '7.2K',
    verified: true,
    tags: ['Beeld', '3D', 'Sculptuur'],
  },
  {
    id: 'c7',
    name: 'Mira Blau',
    handle: '@mirablau',
    avatar: '',
    avatarColor: '#4a9c6e',
    bio: 'Poëzie & citaten · Natuur als metafoor',
    followers: '3.4K',
    tags: ['Citaat', 'Poëzie', 'Natuur'],
  },
]

export const CHAT_ITEMS: ChatItem[] = [
  { id: 'ch1', name: 'Lyra Voss', avatar: '', avatarColor: '#7C3AED', lastMsg: 'Wauw, dat beeld is magisch! 🔮', time: '2m', unread: 3 },
  { id: 'ch2', name: 'Nexus Drift', avatar: '', avatarColor: '#D4A843', lastMsg: 'Ik stuur de stems later vandaag', time: '18m' },
  { id: 'ch3', name: 'Aion Stelios', avatar: '', avatarColor: '#1e6e4e', lastMsg: 'Heb je het essay al gelezen?', time: '1u', unread: 1 },
  { id: 'ch4', name: 'Solara AI', avatar: '', avatarColor: '#9D5FF5', lastMsg: 'Samenwerking klinkt goed 🎬', time: '3u' },
  { id: 'ch5', name: 'Echo Forma', avatar: '', avatarColor: '#c04a8a', lastMsg: 'Bedankt voor de feedback!', time: 'gist.' },
  { id: 'ch6', name: 'Mira Blau', avatar: '', avatarColor: '#4a9c6e', lastMsg: 'Mooi citaat, dankjewel ✨', time: '2d' },
]

export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'like', actor: 'Lyra Voss', avatar: '', avatarColor: '#7C3AED', text: 'vond je post geweldig', time: ago(2), postThumb: 'https://picsum.photos/seed/apsu1/60/60', unread: true },
  { id: 'n2', type: 'follow', actor: 'Nexus Drift', avatar: '', avatarColor: '#D4A843', text: 'volgt jou nu', time: ago(15), unread: true },
  { id: 'n3', type: 'comment', actor: 'Aion Stelios', avatar: '', avatarColor: '#1e6e4e', text: 'reageerde: "Precies wat ik voelde bij het zien."', time: ago(60), postThumb: 'https://picsum.photos/seed/apsu6/60/60', unread: true },
  { id: 'n4', type: 'like', actor: 'Mira Blau', avatar: '', avatarColor: '#4a9c6e', text: 'en 4 anderen liketen je post', time: ago(90), postThumb: 'https://picsum.photos/seed/apsu11/60/60', unread: true },
  { id: 'n5', type: 'live', actor: 'Solara AI', avatar: '', avatarColor: '#9D5FF5', text: 'is live: Generatieve Kunst Workshop', time: ago(120) },
  { id: 'n6', type: 'mention', actor: 'Echo Forma', avatar: '', avatarColor: '#c04a8a', text: 'noemde jou in een reactie', time: ago(1440) },
  { id: 'n7', type: 'follow', actor: 'Vanta Schrijft', avatar: '', avatarColor: '#4a60c0', text: 'volgt jou nu', time: ago(2880) },
]

// Content-type filter (laag 1 in Discover)
export const CONTENT_TYPES = [
  { id: 'all', label: 'Alles' },
  { id: 'image', label: 'Beelden' },
  { id: 'music', label: 'Muziek' },
  { id: 'video', label: 'Video' },
  { id: 'blog', label: 'Blogs' },
  { id: 'quote', label: 'Citaten' },
  { id: 'live', label: 'Live' },
]

// Interesse-categorieën (laag 2 in Discover, ook Compose + Profiel)
export const INTEREST_CATEGORIES = [
  { id: 'spirituality', label: 'Spiritualiteit & Geloof', emoji: '🕊️', color: '#9D5FF5' },
  { id: 'philosophy', label: 'Filosofie', emoji: '🧠', color: '#7C3AED' },
  { id: 'culture', label: 'Cultuur & Samenleving', emoji: '🌍', color: '#4a60c0' },
  { id: 'technology', label: 'Technologie & AI', emoji: '🤖', color: '#1e6e4e' },
  { id: 'art', label: 'Kunst & Illustratie', emoji: '🎨', color: '#7C3AED' },
  { id: 'music', label: 'Muziek & Audio', emoji: '🎵', color: '#D4A843' },
  { id: 'film', label: 'Film & Video', emoji: '🎬', color: '#1e6e4e' },
  { id: 'writing', label: 'Schrijven & Poëzie', emoji: '✍️', color: '#4a60c0' },
  { id: 'finance', label: 'Financiën & Economie', emoji: '📈', color: '#D4A843' },
  { id: 'business', label: 'Zakelijk & Ondernemen', emoji: '💼', color: '#4a60c0' },
  { id: 'health', label: 'Gezondheid & Welzijn', emoji: '🌿', color: '#1e6e4e' },
  { id: 'sport', label: 'Sport & Beweging', emoji: '⚡', color: '#c04a8a' },
  { id: 'food', label: 'Eten & Drinken', emoji: '🍽️', color: '#D4A843' },
  { id: 'fashion', label: 'Mode & Beauty', emoji: '👗', color: '#c04a8a' },
  { id: 'travel', label: 'Reizen & Avontuur', emoji: '✈️', color: '#4a60c0' },
  { id: 'politics', label: 'Wereldpolitiek', emoji: '🗺️', color: '#7C3AED' },
  { id: 'news', label: 'Nieuws & Actualiteit', emoji: '📰', color: '#7a7890' },
  { id: 'science', label: 'Wetenschap & Onderzoek', emoji: '🔬', color: '#1e6e4e' },
  { id: 'nature', label: 'Natuur & Duurzaamheid', emoji: '🌱', color: '#1e6e4e' },
  { id: 'education', label: 'Onderwijs & Groei', emoji: '📚', color: '#9D5FF5' },
]

// Compact-set voor CategoryFeed overlay (6 post-type cats)
export const CATEGORIES = [
  { id: 'cat1', label: 'Beeld', emoji: '🖼️', color: '#7C3AED' },
  { id: 'cat2', label: 'Muziek', emoji: '🎵', color: '#D4A843' },
  { id: 'cat3', label: 'Video', emoji: '🎬', color: '#1e6e4e' },
  { id: 'cat4', label: 'Blog', emoji: '✍️', color: '#4a60c0' },
  { id: 'cat5', label: 'Idee', emoji: '💡', color: '#c04a8a' },
  { id: 'cat6', label: 'Citaat', emoji: '💬', color: '#9D5FF5' },
]
